### ISSUE TITLE
Running composer require stechstudio/laravel-aws-lambda - Install issue 

### ISSUE THREAD

**Issue by ColinDT76** [stechstudio/laravel-aws-lambda#1]
composer require stechstudio/laravel-aws-lambda

Returns 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package stechstudio/laravel-aws-lambda could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

I have minimum-stability is set to dev.
also tried setting the version to dev-master but no Joy

**Comment by prakashkvau** [comment]
Can you submit this to packaglist?

**Comment by bubba-h57** [comment]
Done https://github.com/stechstudio/laravel-aws-lambda
