### ISSUE TITLE
 There are no commands defined in the "aws-lambda" namespace.

### ISSUE THREAD

**Issue by bluevyjohn** [stechstudio/laravel-aws-lambda#2]
@bubba-h57  I am using laravel 5.4, I created a new laravel 5.5 it still same display this error.
php artisan aws-lambda:install / php artisan aws-lambda:package
" There are no commands defined in the "aws-lambda" namespace."

php artisan list no display above command. Please guide me... Thank you.

**Comment by bubba-h57** [comment]
@bluevyjohn I am so sorry I never responded to you. I started working with the bref project and completely forgot about this. I just realized people are using it actually. I will be marking this as deprecated in favor of the https://packagist.org/packages/stechstudio/laravel-bref-bridge package. It is actually stable and had ongoing development and support. Again, I apologize for leaving you hanging.
